create table aluno (id bigint generated by default as identity, nome varchar(255), cep varchar(255), cidade varchar(255), cpf varchar(255), email varchar(255), numero varchar(255), uf varchar(255), cursos_id bigint, primary key (id));
create table curso (id bigint generated by default as identity, curso varchar(255), aluno_id bigint, primary key (id));
create table disciplina (id bigint generated by default as identity, conceito varchar(255), disciplina varchar(255), curso_id bigint, primary key (id));
create table notas (id bigint generated by default as identity, tipo_nota varchar(255), valor_nota varchar(255), disciplina_id bigint, primary key (id));
alter table aluno add constraint FKkkymhxn51rlgggt6m3lfa0xmg foreign key (cursos_id) references curso;
alter table curso add constraint FKbj38yu5d145yfkoituvmtf1w3 foreign key (aluno_id) references aluno;
alter table disciplina add constraint FKkhdiw1swjoa2ml3md0mt8g4sf foreign key (curso_id) references curso;
alter table notas add constraint FKmnt7eyna1oug27dgvn1j0pwqo foreign key (disciplina_id) references disciplina;
