create table aluno (id  bigserial not null, cpf varchar(255), email varchar(255), endereco_bairro varchar(255), endereco_cep varchar(255), endereco_cidade varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), endereco_uf varchar(255), matricula int8, nome varchar(255), primary key (id));
create table aluno_cursos (aluno_id int8 not null, cursos_id int8 not null);
create table curso (id  bigserial not null, curso varchar(255), primary key (id));
create table curso_disciplinas (curso_id int8 not null, disciplinas_id int8 not null);
create table disciplina (id  bigserial not null, codigo varchar(255), conceito varchar(255), disciplina varchar(255), primary key (id));
create table disciplina_notas (disciplina_id int8 not null, notas_id int8 not null);
create table notas (id  bigserial not null, tipo_nota varchar(255), valor_nota varchar(255), primary key (id));
alter table aluno_cursos add constraint UK_qnbbvcawm3ixrh4olq9p4rigt unique (cursos_id);
alter table curso_disciplinas add constraint UK_53gk6o7w8n5ca42u12q0pgcx8 unique (disciplinas_id);
alter table disciplina_notas add constraint UK_10htxolbngt164flmjqyodpbh unique (notas_id);
alter table aluno_cursos add constraint FK9hbn0t6pgg0oe7d4vdwxoynvn foreign key (cursos_id) references curso;
alter table aluno_cursos add constraint FK5qln5vxflay0g315k0jjwu7mh foreign key (aluno_id) references aluno;
alter table curso_disciplinas add constraint FKevhx0g5kl3xss8i5xbkqi7v21 foreign key (disciplinas_id) references disciplina;
alter table curso_disciplinas add constraint FKhc6evgy4o6jysjna05vl0o5wd foreign key (curso_id) references curso;
alter table disciplina_notas add constraint FKc44c1t8jl0h1ara1fcm2rpov foreign key (notas_id) references notas;
alter table disciplina_notas add constraint FKqmwqrnee2resq5ieoo8b1rc70 foreign key (disciplina_id) references disciplina;
